name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.5
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.5"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^4.0.6
  flutter_local_notifications: ^12.0.3
  rxdart: ^0.27.5

  path_provider: ^2.0.11
  package_info_plus: ^3.0.1
  sensors: ^2.0.3
  share_plus: ^6.2.0
  chopper: ^4.0.6
  collection: ^1.16.0

dev_dependencies:
  lint: ^1.10.0
